apiVersion: apps/v1 #APIのバージョン
kind: Deployment #リソースの種類
metadata:
  name: test-nginx #名前を付ける
spec:
  selector: #どのPodを起動するか
    matchLabels:
      app: nginx #テンプレートを指定
  replicas: 2 #レプリカ数（Podの数）
  template: #作成されるPodのテンプレート
    metadata:
      labels:
        app: nginx #Labelを付ける
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80 #ポート番号
